stages:
- name: Build and publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: nominatim-docker:${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34593
timeout: 60
notification: {}
