kind: Service
apiVersion: apps/v1beta2
metadata:
  name: nominatim-docker-service
  namespace: default
spec:
  selector:
    app: nominatim-docker-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1beta2
kind: Job
metadata:
  name: nominatim-docker
  namespace: default
  labels:
    app: nominatim-docker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nominatim-docker-app
  template:
    metadata:
      labels:
        app: nominatim-docker-app
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - args:
        - /bin/bash
        - -c
        - rm -rf /data/postgresdata && curl -L https://download.geofabrik.de/europe/monaco-latest.osm.pbf -o /data/extract.osm.pbf && cd /app && ./init-rancher.sh /data/extract.osm.pbf postgresdata 4
      - name: nominatim-docker-app
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /data
          name: vol1
      volumes:
      - name: vol1
        persistentVolumeClaim:
          claimName: 2019-07-24-nominatim-docker-pvc--ga-htz-fsn02