kind: Service
apiVersion: v1
metadata:
  name: nominatim-docker-service
  namespace: default
spec:
  selector:
    app: nominatim-docker
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nominatim-docker-deployemnt
  namespace: default
  labels:
    app: nominatim-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nominatim-docker
  template:
    metadata:
      labels:
        app: nominatim-docker
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: nominatim-docker
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /data
          name: vol1
      volumes:
      - name: vol1
        persistentVolumeClaim:
          claimName: 2019-07-24-nominatim-docker-pvc--ga-htz-fsn02